### ISSUE TITLE
Register on Packagist

### ISSUE THREAD

**Issue by Hywan** [atoum/ruler-extension#2]

**Comment by agallou** [comment]
Before that. Should we move the repo to the atoum organization ? ping @jubianchi @mageekguy

**Comment by Hywan** [comment]
Nop, there are several extensions which do not belong to the atoum organization (all of them actually).

**Comment by jubianchi** [comment]
@Hywan I moved some of them to the org.

To decide wether the extension could be hosted in the org, I asked myself the following question:
- Is the ext. compliant with atoum mantra: "Modern, simple, Intuitive"?
- Is it using the same CS as atoum?
- Is it built using same structure as atoum?
- Is it covered by tests?
- Does it work without composer (not required but if the extension is standalone, it's better)?

If an extension matches (at least) those thing, we can consider moving it to the org ;)

**Comment by agallou** [comment]
the only thing that not matches those tests is the "same CS as atoum".
So when I fix this I move the repository ? Is that ok ?

**Comment by jubianchi** [comment]
:+1: for me

**Comment by Hywan** [comment]
:+1: for me too.

**Comment by agallou** [comment]
The extension is now on packagist. The issue can be closed : https://packagist.org/packages/atoum/ruler-extension

**Comment by Hywan** [comment]
\o/
